services:
  - type: web
    name: studyhub-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5002

  - type: web
    name: studyhub-frontend
    env: static
    buildCommand: "cd frontend/studyhub-frontend && npm install && npm run build"
    staticPublishPath: frontend/studyhub-frontend/dist/studyhub-frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html